# Site settings
title: 박천웅
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: 박천웅
#user_description: I'm a Software Engineer from Argentina, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in world of Giving Circles working with Grapevine, a California based startup trying to improve the world through collaborative giving. I'm the first engineer they hired to work on the platform. 
user_description: 음..
user_title: DevSecOps Engineer
email: cheongwoong21@naver.com
# twitter_username: lorem_ipsum
instagram_username: 1000_woong_
#facebook_username: mauricio.urraco
# linkedin_username: murraco
github_username:  CheonWoong-Park
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

